#!/usr/bin/env python3
import io
import json
import sys
import textwrap

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def format_cents(cents):
    return f"${cents / 100:,.2f}"


def draw_label(pdf, x, y, label, value):
    pdf.setFillColor(HexColor("#6B7280"))
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(x, y, label)
    pdf.setFillColor(HexColor("#111827"))
    pdf.setFont("Helvetica", 10)
    pdf.drawString(x, y - 14, value)


def main():
    invoice = json.load(sys.stdin)
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    page_width, page_height = letter

    left = 54
    right = page_width - 54
    y = page_height - 54

    pdf.setFillColor(HexColor("#111827"))
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(left, y, "BudgetFlow")

    pdf.setFillColor(HexColor("#2563EB"))
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawRightString(right, y, "INVOICE")

    y -= 38
    pdf.setStrokeColor(HexColor("#D1D5DB"))
    pdf.line(left, y, right, y)

    y -= 30
    draw_label(pdf, left, y, "BILL TO", invoice["customer_name"])
    pdf.setFont("Helvetica", 10)
    pdf.drawString(left, y - 30, invoice["customer_email"] or "No email provided")
    pdf.drawString(left, y - 44, invoice["customer_phone"] or "No phone provided")

    draw_label(pdf, right - 170, y, "INVOICE NUMBER", invoice["invoice_no"])
    draw_label(pdf, right - 170, y - 52, "INVOICE DATE", invoice["invoice_date"])
    draw_label(pdf, right - 170, y - 104, "DUE DATE", invoice["due_date"])
    draw_label(pdf, right - 170, y - 156, "STATUS", invoice["status"].upper())

    y -= 220
    pdf.setFillColor(HexColor("#1F2937"))
    pdf.rect(left, y, right - left, 24, fill=1, stroke=0)
    pdf.setFillColor(HexColor("#FFFFFF"))
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(left + 10, y + 7, "DESCRIPTION")
    pdf.drawRightString(right - 10, y + 7, "AMOUNT")

    y -= 28
    pdf.setFillColor(HexColor("#111827"))
    pdf.setFont("Helvetica", 10)

    description_lines = textwrap.wrap(invoice["description"], width=62) or [""]
    for line in description_lines:
        pdf.drawString(left + 10, y, line)
        y -= 14

    pdf.drawRightString(right - 10, y + 14, format_cents(invoice["amount_cents"]))

    y -= 18
    pdf.setStrokeColor(HexColor("#D1D5DB"))
    pdf.line(left, y, right, y)

    y -= 30
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawRightString(right - 10, y, f"TOTAL: {format_cents(invoice['amount_cents'])}")

    pdf.setFillColor(HexColor("#6B7280"))
    pdf.setFont("Helvetica", 9)
    pdf.drawCentredString(
        page_width / 2,
        36,
        "Generated by BudgetFlow Accounting System",
    )

    pdf.save()
    sys.stdout.buffer.write(buffer.getvalue())


if __name__ == "__main__":
    main()